build:
  maxIssues : 0
  weights:
    complexity: 5
    formatting: 2
    comments: 0
    empty-blocks: 0
    exceptions: 2
    naming: 2
    performance: 2
    potential-bugs: 0
    style-bugs: 5

comments:
  CommentOverPrivateProperty:
    active: false
  CommentOverPrivateFunction:
    active: false
  UndocumentedPublicClass:
    active: false
    excludes: "**/src/test/**/*.kt,**/src/androidTest/**/*.kt"
    includes: "**/src/main/**/*.kt"
  UndocumentedPublicFunction:
    active: false
    excludes: "**/src/test/**/*.kt,**/src/androidTest/**/*.kt"
    includes: "**/src/main/**/*.kt"
  UndocumentedPublicProperty:
    active: false
    excludes: "**/src/test/**/*.kt,**/src/androidTest/**/*.kt"
    includes: "**/src/main/**/*.kt"

complexity:
  StringLiteralDuplication:
    active: true
    excludes: "**/src/test/**/*.kt,**/src/androidTest/**/*.kt"
    threshold: 5
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  ComplexInterface:
    active: true
    threshold: 25
    includeStaticDeclarations: false
  ComplexMethod:
    active: true
    threshold: 25
    ignoreSingleWhenExpression: true
  MethodOverloading:
    active: true
    threshold: 5
  ComplexCondition:
    active: true
    threshold: 4
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    threshold: 268
  LongMethod:
    active: true
    threshold: 32
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: false
  NestedBlockDepth:
    active: true
    threshold: 5
  TooManyFunctions:
    active: true
    thresholdInFiles: 48
    thresholdInClasses: 32
    thresholdInInterfaces: 32
    thresholdInObjects: 32
    thresholdInEnums: 24

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames: 'toString,hashCode,equals,finalize'
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: true
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions: 'IllegalArgumentException,IllegalStateException,IOException'
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - Error
      - Exception
      - NullPointerException
      - Throwable
      - RuntimeException

formatting:
  active: true
  android: false
  autoCorrect: true
  MaximumLineLength:
    active: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z$][a-zA-Z_$]*$'
  ForbiddenClassName:
    active: false
    forbiddenName: ''
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  FunctionNaming:
    active: true
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
  MatchingDeclarationName:
    active: true
  MemberNameEqualsClassName:
    active: false
    ignoreOverridden: true
  ObjectPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: false
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z\d]*'
    privatePropertyPattern: '(_)?[a-z][A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 64
  VariableMinLength:
    active: false
    minimumVariableNameLength: 1
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  MissingWhenCase:
    active: true
  RedundantElseInWhen:
    active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
    excludeAnnotatedProperties: ""
    ignoreOnClassesPattern: ""
  UnconditionalJumpStatementInLoop:
    active: false
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: true
    excludes: "**/src/test/**/*.kt,**/src/androidTest/**/*.kt"
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  CollapsibleIfStatements:
    active: true
  EqualsNullCall:
    active: true
  ForbiddenImport:
    active: false
    imports: ''
  ForbiddenComment:
    active: true
    values: 'TODO:,FIXME:,STOPSHIP:,@author'
  FunctionOnlyReturningConstant:
    active: true
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  LibraryCodeMustSpecifyReturnType:
    active: true
  MaxLineLength:
    active: true
    excludeCommentStatements: true
    excludeImportStatements: true
    maxLineLength: 300
  MagicNumber:
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers: '-1,0,1,2,100,1000'
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreNamedArgument: true
  ModifierOrder:
    active: true
  MayBeConst:
    active: true
  NestedClassesVisibility:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryInheritance:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
    allowedNames: "(_|ignored|expected)"
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: true
  RedundantVisibilityModifierRule:
    active: false
  ReturnCount:
    active: true
    max: 2
    excludedFunctions: "equals"
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: false
  ThrowsCount:
    active: true
    max: 2
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: false
    excludeAnnotatedClasses: ""
  WildcardImport:
    active: true
    excludeImports: 'java.util.*,kotlinx.android.synthetic.*, io.github.justinlewis.app.*, io.github.justinlewis.*, android.*, com.firebase.*'
